### ISSUE TITLE
Task:  UX Design: Structure

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/CI_PP4_Financial_Planner#4]
EPIC:  UX

As a site designer I want to plan out interaction design and information architecture for site users, so the architecture makes it easire for users of the site.

### Acceptance Criteria
* Page hierarchy and navigation is outlined in wireframes
* (Initial) data structures are described in high-level data models
### Tasks
- [x] Design proposed flow for site navigation
- [x]  Design hgh-level information architectre (high level data models)

**Comment by DeeMcCart** [comment]
22/10/23:  hmmm not sure this is really a task at all, think its covered in wireframes and LucdChart ERDs

**Comment by Blackmercii2** [comment]
Hi have you sorted this out yet?

**Comment by DeeMcCart** [comment]
HI Doreen I just wanted to say thank you for your interest in my Financial
Planner project.  This first version is being created as an academic
project so I need to work alone on it.
My intention is to create an MVP for academic submission.
However once submitted in early December, I would like to develop it
further into a consumer product.

Is this something you have an interest in?
Thanks
Deirdre

**Comment by DeeMcCart** [comment]
30/10/23 (Sprint 5 retrospective) this issue was worked on during sprint 5, so is largely completd.  Moving to 'review' for sprint 6 as want to ensure that the wireframes and planned data structures include items needed for Release 1 (personalised Financial Planner with ability to track actions and bookmarks etc at the specific user profile level for registered users)
